server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: earliest
      group-id: 0
